### ISSUE TITLE
ABP项目重命名后出现几个问题

### ISSUE THREAD

**Issue by tanshanli** [liamwang/RenameTool#1]
1.nuget不能使用
2.项目中所有图片无法打开了
3.字体文件失效
我的环境：win10、vs2017，abp zero 3.1.4  mvc5
解决方案：需要替换.nuget文件夹，和项目中所有图片及字体文件即可
如果工具能修复下最好。

**Comment by liamwang** [comment]
@tanshanli  将 nuget 加入到  appsettings.json 中的 IgnoreFolders 配置中，字体文件扩展名加到  IgnoreExtensions 中应该就可以了。
